### ISSUE TITLE
Closing-channel.go  result ??

### ISSUE THREAD

**Issue by mudongliang** [mmcgrana/gobyexample#101]
This is the result of gobyexample/example/closing-channels/closing-channels.go in your website !
$ go run closing-channels.go 
sent job 1
received job 1
sent job 2
received job 2
sent job 3
received job 3
sent all jobs
received all jobs

I want to ask whether the result is always the same , or different at runtime !

**Comment by andradei** [comment]
It would always be the same. Even though there is a part of the code that is run on a separate thread, it runs in sync with the main thread.

**Comment by Bruce-sz** [comment]
I carefully check my code, and the "GitHub" code is the same, but why I always get the following results：
[ `go run closechan.go` | done: 288.088473ms ]
	sent job 1
	sent job 2
	sent job 3
	sent all jobs
	received job 1
	received job 2
	received job 3
	received all jobs

**Comment by Bruce-sz** [comment]
I carefully check the code, and the "GitHub" code is the same, but why I always get the following results：
[ `go run closechan.go` | done: 307.238771ms ]
	sent job 1
	sent job 2
	sent job 3
	sent all jobs
	received job 1
	received job 2
	received job 3
	received all jobs

**Comment by pawanrawal** [comment]
I think this is because the channel is buffered, hence all jobs are sent first and then received. IMHO , its a bug @mmcgrana

**Comment by andradei** [comment]
Also, sometimes the execution of so little code is "too fast" and the result always comes out in order _as though it didn't run on separate threads_. But yeah, it could also be a bug.

**Comment by mmcgrana** [comment]
The exact order observed when you run the code is the result of preemption behavior that may vary by environment / version / platform etc. The code as written certainly _could_ produce the interleaving documented on the site. If you want to see specific interleavings in action, you can try adding sleeps. For example: https://play.golang.org/p/JJaNaB5-h8.

I'm not going to try to tweak the code on the site further to produce specific interleavings though, since as mentioned above it depends on things that may vary over time like how the Go scheduler works.
