### ISSUE TITLE
Unhack italics around links

### ISSUE THREAD

**Issue by mmcgrana** [mmcgrana/gobyexample#182]
See 37740d69. Maybe upgrade to v2 of BlackFriday.

**Comment by eliben** [comment]
I looked into upgrading to v2 of BlackFriday, but their module release of v2 is currently somewhat busted -- see https://github.com/russross/blackfriday/issues/500

Since the italics issue doesn't seem major, I'd suggest waiting until they unbreak their module stuff because at this point it makes sense to use modules and not the older packaging stuff.
