### ISSUE TITLE
Opening links brings up raw HTML instead

### ISSUE THREAD

**Issue by mm-2018** [mmcgrana/gobyexample#210]
When I try to create the website using the steps in the README.md, it is successful. I can access public/index.html, which opens automatically via a GUI file manager on Linux, but clicking on any of the links brings up raw HTML files instead of the websites formatted accordingly. I believe this is because the files under the public folder all do not end with .html. I'm wondering if you can try and fix this.

**Comment by Ryanthegiantlion** [comment]
I experienced the same when opening in chrome. A workaround is to open in firefox.

**Comment by mmcgrana** [comment]
You can also workaround this issue using a minimal web server: https://github.com/mmcgrana/gobyexample/issues/218.

It's good to know Firefox works as well, I didn't realize that!

I'm not planning to change the core HTML generation since the primary target of that output is the hosted website. If someone wanted to propose a change to the Readme to note the best ways to views the files locally I'd consider that.
