### ISSUE TITLE
Make available offline

### ISSUE THREAD

**Issue by kreempuff** [mmcgrana/gobyexample#218]
First off, thank you for this. I reference it often

I was wondering if you'd be open to making it available offline, with a service worker.

**Comment by mmcgrana** [comment]
Hi. Thanks for the kind words!

I'm not planning to make the site available offline specifically via service workers, to minimize complexity.

However you should be able to use it offline since it's a static site:

```console
$ git clone https://github.com/mmcgrana/gobyexample.git
$ cd gobyexample/public
$ ls
$ open index.html
```

The only tricky part is dealing with the HTML files not having `.html` extensions. But you can work around this with e.g. a local web server that serves files with the `text/html` MIME type by default:

```console
$ cd gobyexample/public

$ cat > server.py <<EOF
#!/usr/bin/python
import SimpleHTTPServer
import SocketServer
PORT = 8000
Handler = SimpleHTTPServer.SimpleHTTPRequestHandler
Handler.extensions_map.update({
    '': 'text/html',
});
httpd = SocketServer.TCPServer(("", PORT), Handler)
httpd.serve_forever()
EOF

$ python server.py

$  open http://127.0.0.1:8000
```
