### ISSUE TITLE
Stateful Goroutines - Why passing pointer to channel?

### ISSUE THREAD

**Issue by anayrat** [mmcgrana/gobyexample#221]
Hello,
First of all thanks for your website, it is useful for beginner like me :)

I wonder why do you use a pointer when you create a channel?
https://github.com/mmcgrana/gobyexample/blob/c43c319d2684b5ad7601e97b5fc2ba54552de4c3/examples/stateful-goroutines/stateful-goroutines.go#L46

I tried without passing pointer and it seemed to work : 
https://play.golang.org/p/saQTLpdIgp2

Am I wrong?

I tried to understand why it was like this and I stumbled on theses stackoverflow posts:
https://stackoverflow.com/a/44351176
https://stackoverflow.com/questions/41178729/why-passing-pointers-to-channel-is-slower

Thanks!

**Comment by anayrat** [comment]
Oh, is it due to `atomic.AddUint64(&readOps, 1)` call?

**Comment by mmcgrana** [comment]
Hmm interesting.

I was using a pointer here because the `readOp` - which is a combination of a key and `rest` channel, is a struct that you logically want to share between sending and receiving side of the `reads` channel (in particular, the two sides of the `reads` channel need to communicate via the same `resp` channel, and there's no need to have two copies of the `key` to read). It wasn't initially clear to me that passing by value into the channel - which would do a copy - would work as expected. I think it _does_ work because the `rest`channel itself has reference semantics (it's just a pointer, so copying it is OK).

@eliben curious what you think about this one.

**Comment by eliben** [comment]
Channels have reference semantics. This is the reason we pass them to functions by value, like one of the [earlier samples here](https://gobyexample.com/channel-synchronization).

When I see a pointer being used for an object passed around, I expect both sides having write access to it. This doesn't apply to channels, channels are implicitly shared by their very nature. Moreover, it's not idiomatic to just pass pointers around on channels because then you need mutexes to protect access to them and the whole "share by communicating" idea goes off the rails.

So I think I would vote for removing the pointers here.
