### ISSUE TITLE
bug of go when pass parameter in for loop

### ISSUE THREAD

**Issue by gitbufenshuo** [mmcgrana/gobyexample#267]
https://github.com/mmcgrana/gobyexample/blob/fe361d879b570cb0ed0303173a078a634d617409/examples/worker-pools/worker-pools.go#L34

should be 
`
workerID := w
`
`
go worker(workerID, jobs, results)
`

**Comment by eliben** [comment]
Thanks for the report.

I believe this isn't a bug, because `w` is used by value here - it's not captured in a closure. This will work correctly.

However, I agree this could be confusing so we should either clarify the behavior with a comment, or rephrase the code in a slightly different way. I prefer changing the comment.

Therefore I suggest to rename this issue to reflect that it's a documentation problem, not a bug in the code

**Comment by gitbufenshuo** [comment]
> Thanks for the report.
> 
> I believe this isn't a bug, because `w` is used by value here - it's not captured in a closure. This will work correctly.
> 
> However, I agree this could be confusing so we should either clarify the behavior with a comment, or rephrase the code in a slightly different way. I prefer changing the comment.
> 
> Therefore I suggest to rename this issue to reflect that it's a documentation problem, not a bug in the code

Oh. You are right. I just made a mistake about this. 
Thanks for replying.
Closing now.
