### ISSUE TITLE
WaitGroup: worker should not take wg *sync.WaitGroup

### ISSUE THREAD

**Issue by peterbourgon** [mmcgrana/gobyexample#278]
[Coming from this reddit comment](https://www.reddit.com/r/golang/comments/d4q0n2/should_syncwaitgroup_be_passed_to_function/), I think the WaitGroup example could be improved by having the worker function just be a worker function, and performing the wg.Done an anonymous goroutine in the calling context.

You could still mention that sync.WaitGroups need to be passed by pointer at the bottom of the example, if you felt that was important.

**Comment by eliben** [comment]
Thanks for the suggestion, @peterbourgon.

The truth is, the `worker` function only exists to demonstrate passing `WorkGroup` by pointer since this is such a common gotcha (people pass it by value and it doesn't behave as you'd expect). Otherwise we'd just inline `worker` into an function literal launched by the `go` statement. Moving `WorkGroup` out of `worker` will render `worker` rather useless.

**Comment by peterbourgon** [comment]
But that's entirely the point: passing a WaitGroup to a function, even correctly, is a code smell, because functions generally shouldn't be responsible for their own concurrency or asynchronous, that should generally be orchestrated by the caller. As most of the comments in that Reddit link also, IMO correctly, pointed out.

I understand the tension in your mandate, here, between pointing out a common gotcha vs. demonstrating the best way to do things. It's your site, so obviously do what makes sense to you.

**Comment by eliben** [comment]
I ran a `grep` on the Go repo to see if `WaitGroup` is passed to functions. There are several places, mostly in tests, but not only. The same shows up in the kubernetes repo.

I'll spend some more time thinking about this, and ask around. It's a tricky balance here.

**Comment by eliben** [comment]
I've finally revisited this and decided to go with the more idiomatic approach as you've suggested, @peterbourgon. Thank you for bringing this up!

I still added a note of passing a WaitGroup by pointer if needed, because I believe it's a very important gotcha with this type. Please feel free to open a separate issue if you have additional suggestions for improving this example.
