### ISSUE TITLE
support go mod (module)

### ISSUE THREAD

**Issue by satriyop** [mmcgrana/gobyexample#333]
Is there any plan to support module in this project ? I tried to fork this to Indonesian and when start using module it has error when build. Thank you.

**Comment by eliben** [comment]
It's not clear what you are asking, can you please add more details about the errors you're seeing?

The Go code in the examples are standalone `.go` files with no external dependencies, so it doesn't seem like it should matter if you use Go modules or not.

Are you talking about `tools/`?

**Comment by satriyop** [comment]
@eliben , I am sorry if my description was not clear enough. yes, i am talking about tools/.

The issue begin with i enable module by go mod and go mod vendor. Somehow (this is the part that i don't understand exactly, the vendor/pymentize is no longer in the directory). 

I tried to build by tools/build and it returning error (looking for vendor/pygmentize).

I am under assumption that it has something to do when I am enabling the module however, I could be wrong.

**Comment by eliben** [comment]
> The issue begin with i enable module by go mod and go mod vendor

Why do you do this?

The `vendor` directory at the root of gobyexample is not a proper Go `vendor` directory - rather it has Python 3rd party dependencies.

`tools` doesn't use modules at this time, since these are just standalone tools - not importable modules.  Their  only external dependency is the `blackfriday` package, which you could `go get` before running the tools.

**Comment by satriyop** [comment]
Understood. I will close this issue now. Thanks
